name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15  # Make sure to use the latest version
      with:
        versionSpec: '5.x'  # or specify a specific version like '5.1.0'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
      run: |
        gittools/actions/gitversion/execute@v0.9.15
        echo "major=${{ steps.gitversion.outputs.major }}" >> $GITHUB_OUTPUT
        echo "minor=${{ steps.gitversion.outputs.minor }}" >> $GITHUB_OUTPUT
        echo "patch=${{ steps.gitversion.outputs.patch }}" >> $GITHUB_OUTPUT
        echo "prereleasetag=${{ steps.gitversion.outputs.preReleaseTag }}" >> $GITHUB_OUTPUT
        echo "prereleasetagwithdash=${{ steps.gitversion.outputs.preReleaseTagWithDash }}" >> $GITHUB_OUTPUT
        echo "fullsemver=${{ steps.gitversion.outputs.fullSemVer }}" >> $GITHUB_OUTPUT
        echo "informationalversion=${{ steps.gitversion.outputs.informationalVersion }}" >> $GITHUB_OUTPUT
        echo "assemblysemver=${{ steps.gitversion.outputs.assemblySemVer }}" >> $GITHUB_OUTPUT

    - name: Display GitVersion info
      run: |
        echo "Major: ${{ steps.gitversion.outputs.major }}"
        echo "Minor: ${{ steps.gitversion.outputs.minor }}"
        echo "Patch: ${{ steps.gitversion.outputs.patch }}"
        echo "PreReleaseTag: ${{ steps.gitversion.outputs.prereleasetag }}"
        echo "PreReleaseTagWithDash: ${{ steps.gitversion.outputs.prereleasetagwithdash }}"
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullsemver }}"
        echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalversion }}"
        echo "AssemblySemVer: ${{ steps.gitversion.outputs.assemblysemver }}"

    - name: Restore dependencies
      run: dotnet restore useless-stuff

    - name: Build
      run: dotnet build useless-stuff --configuration Release --no-restore

    - name: Test
      run: dotnet test useless-stuff-tests --no-restore --verbosity normal