name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install jq
      run: sudo apt-get install -y jq
    
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15  # Make sure to use the latest version
      with:
        versionSpec: '5.x'  # or specify a specific version like '5.1.0'

    - name: Determine Version
      id: gitversion
      run: |
        echo "version_info<<EOF" >> $GITHUB_OUTPUT
        dotnet gitversion
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Parse Version Info
      shell: bash
      run: |
        echo "Version is ${{ fromJson(steps.gitversion.outputs).Major }}"

    - name: Display GitVersion info
      run: |
        echo "Value: ${{ steps.gitversion.outputs }}"
