name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Restore dependencies
      run: dotnet restore useless-stuff

    - name: Build
      run: dotnet build useless-stuff --configuration Release --no-restore

    # If the tests fail this will just exit the process
    - name: Test
      run: dotnet test useless-stuff-tests --no-restore --verbosity normal

    - name: Install jq
      run: sudo apt-get install -y jq
    
    - name: Setup and Determine Version
      if: github.ref == 'refs/heads/main' 
      id: gitversion
      run: |
        # Setup GitVersion
        dotnet tool install --global GitVersion.Tool --version 5.*
        
        # Determine Version and Output
        dotnet gitversion 2>&1 | tee gitversion_output.json
        echo "version_info<<EOF" >> $GITHUB_OUTPUT
        cat gitversion_output.json >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Parse Version Info
      id: parse_version
      shell: bash
      run: |
        echo "version=$(echo '${{ steps.gitversion.outputs.version_info }}' | jq -r '.MajorMinorPatch')" >> $GITHUB_OUTPUT

    - name: Create Tag
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag -a "v${{ steps.parse_version.outputs.version }}" -m "Release version ${{ steps.parse_version.outputs.version }}"
        git push origin "v${{ steps.parse_version.outputs.version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
