name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.14
      with:
        versionSpec: 'latest'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.14

    - name: Display GitVersion info
      run: |
        echo "Major: ${{ steps.gitversion.outputs.major }}"
        echo "Minor: ${{ steps.gitversion.outputs.minor }}"
        echo "Patch: ${{ steps.gitversion.outputs.patch }}"
        echo "PreReleaseTag: ${{ steps.gitversion.outputs.preReleaseTag }}"
        echo "PreReleaseTagWithDash: ${{ steps.gitversion.outputs.preReleaseTagWithDash }}"
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
        echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"
        echo "AssemblySemVer: ${{ steps.gitversion.outputs.assemblySemVer }}"

    - name: Restore dependencies
      run: dotnet restore useless-stuff

    - name: Build
      run: dotnet build useless-stuff --configuration Release --no-restore

    - name: Test
      run: dotnet test useless-stuff-tests --no-restore --verbosity normal