name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Set Output
      id: my_step
      run: |
        echo "my_output=some value" >> $GITHUB_OUTPUT

    - name: Use Output
      run: |
        echo "The output was ${{ steps.my_step.outputs.my_output }}"
    
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15  # Make sure to use the latest version
      with:
        versionSpec: '5.x'  # or specify a specific version like '5.1.0'

    - name: Determine Version
      id: gitversion
      run: |
        version_info=$(dotnet gitversion)
        echo version_info >> $GITHUB_OUTPUT

    - name: Display GitVersion info
      run: |
        echo "Value: ${{ steps.gitversion.outputs }}"
