name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "YourStrong@Passw0rd"
        ports:
          - 1433:1433
        # Health check to wait for SQL Server to be ready
        options: >-
          --health-cmd="/opt/mssql-tools/bin/sqlcmd -U sa -P YourStrong@Passw0rd -Q 'SELECT 1' || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install SQL Server Command Line Tools
      run: |
        sudo apt-get update && sudo apt-get install -y mssql-tools unixodbc-dev
    
    - name: Initialize Database
      run: |
        SQLCMD -S localhost -U sa -P YourStrong@Passw0rd -Q "CREATE DATABASE YourTestDB;"
        # Add your schema creation scripts here or run migrations
    
    - name: Restore dependencies
      run: dotnet restore useless-stuff

    - name: Build
      run: dotnet build useless-stuff --configuration Release --no-restore

    # If the tests fail this will just exit the process
    - name: Test
      run: dotnet test useless-stuff-tests --no-restore --verbosity normal

    - name: Determine Version
      if: github.ref == 'refs/heads/main'
      id: gitversion
      run: |
        # Update package list and install jq
        sudo apt-get update
        sudo apt-get install -y jq || { echo "Failed to install jq"; exit 1; }
        
        # Setup GitVersion
        dotnet tool install --global GitVersion.Tool --version 5.* || { echo "Failed to install GitVersion"; exit 1; }
        
        # Determine Version
        output=$(dotnet gitversion 2>&1)
        if [ $? -ne 0 ]; then
          echo "Failed to determine version with GitVersion"
          exit 1
        fi
        
        # Parse Version Info
        version=$(echo "$output" | jq -r '.MajorMinorPatch')
        
        # Set Output
        echo "version=$version" >> $GITHUB_OUTPUT
      shell: bash

    - name: Pack Project
      if: github.ref == 'refs/heads/main'
      run: dotnet pack useless-stuff\\useless-stuff.csproj --configuration Release --output artifacts -p:packageVersion=${{ steps.gitversion.outputs.version }}

    - name: Setup NuGet
      if: github.ref == 'refs/heads/main'
      uses: nuget/setup-nuget@v1

    - name: Add GitHub Package Source
      if: github.ref == 'refs/heads/main'
      run: |
        dotnet nuget add source --username soundman10000 --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/soundman10000/index.json"

    - name: Push to GitHub Packages
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github

    - name: Create Tag
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag -a "v${{ steps.gitversion.outputs.version }}" -m "Release version ${{ steps.gitversion.outputs.version }}"
        git push origin "v${{ steps.gitversion.outputs.version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
