name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15  # Make sure to use the latest version
      with:
        versionSpec: '5.x'  # or specify a specific version like '5.1.0'

    - name: Determine Version
      id: gitversion
      run: |
        output=$(dotnet gitversion | tee /dev/tty)
        echo "major=$(echo "$output" | grep -oP '(?<=Major: )\d+')" >> $GITHUB_OUTPUT
        echo "minor=$(echo "$output" | grep -oP '(?<=Minor: )\d+')" >> $GITHUB_OUTPUT
        echo "patch=$(echo "$output" | grep -oP '(?<=Patch: )\d+')" >> $GITHUB_OUTPUT
        echo "prereleasetag=$(echo "$output" | grep -oP '(?<=PreReleaseTag: )\S+')" >> $GITHUB_OUTPUT
        echo "prereleasetagwithdash=$(echo "$output" | grep -oP '(?<=PreReleaseTagWithDash: )\S+')" >> $GITHUB_OUTPUT
        echo "fullsemver=$(echo "$output" | grep -oP '(?<=FullSemVer: )\S+')" >> $GITHUB_OUTPUT
        echo "informationalversion=$(echo "$output" | grep -oP '(?<=InformationalVersion: )\S+')" >> $GITHUB_OUTPUT
        echo "assemblysemver=$(echo "$output" | grep -oP '(?<=AssemblySemVer: )\S+')" >> $GITHUB_OUTPUT

    - name: Display GitVersion info
      run: |
        echo "Major: ${{ steps.gitversion.outputs.major }}"
        echo "Minor: ${{ steps.gitversion.outputs.minor }}"
        echo "Patch: ${{ steps.gitversion.outputs.patch }}"
        echo "PreReleaseTag: ${{ steps.gitversion.outputs.prereleasetag }}"
        echo "PreReleaseTagWithDash: ${{ steps.gitversion.outputs.prereleasetagwithdash }}"
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullsemver }}"
        echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalversion }}"
        echo "AssemblySemVer: ${{ steps.gitversion.outputs.assemblysemver }}"

    - name: Restore dependencies
      run: dotnet restore useless-stuff

    - name: Build
      run: dotnet build useless-stuff --configuration Release --no-restore

    - name: Test
      run: dotnet test useless-stuff-tests --no-restore --verbosity normal