name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Restore dependencies
      run: dotnet restore useless-stuff

    - name: Build
      run: dotnet build useless-stuff --configuration Release --no-restore

    # If the tests fail this will just exit the process
    - name: Test
      run: dotnet test useless-stuff-tests --no-restore --verbosity normal

    - name: Determine Version
      if: github.ref == 'refs/heads/main'
      id: gitversion
      run: |
        # Update package list and install jq
        sudo apt-get update
        sudo apt-get install -y jq || { echo "Failed to install jq"; exit 1; }
        
        # Setup GitVersion
        dotnet tool install --global GitVersion.Tool --version 5.* || { echo "Failed to install GitVersion"; exit 1; }
        
        # Determine Version
        output=$(dotnet gitversion 2>&1)
        if [ $? -ne 0 ]; then
          echo "Failed to determine version with GitVersion"
          exit 1
        fi
        
        # Parse Version Info
        version=$(echo "$output" | jq -r '.MajorMinorPatch')
        
        # Set Output
        echo "version=$version" >> $GITHUB_OUTPUT
      shell: bash

    - name: Pack Project
      if: github.ref == 'refs/heads/main'
      run: dotnet pack useless-stuff\\useless-stuff.csproj --configuration Release --output artifacts -p:packageVersion=${{ steps.gitversion.outputs.version }}

    - name: Setup NuGet
      if: github.ref == 'refs/heads/main'
      uses: nuget/setup-nuget@v1

    - name: Add GitHub Package Source
      if: github.ref == 'refs/heads/main'
      run: |
        nuget sources Add -Name "GitHub" -Source "https://nuget.pkg.github.com/OWNER/index.json" -UserName OWNER -Password ${{ secrets.GITHUB_TOKEN }} -StorePasswordInClearText

    - name: Push to GitHub Packages
      if: github.ref == 'refs/heads/main'
      run: |
        nuget push "artifacts/*.nupkg" -Source "GitHub" -SkipDuplicate
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Tag
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag -a "v${{ steps.gitversion.outputs.version }}" -m "Release version ${{ steps.gitversion.outputs.version }}"
        git push origin "v${{ steps.gitversion.outputs.version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}