name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install jq
      run: sudo apt-get install -y jq
    
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      run: |
        output=$(dotnet gitversion 2>&1)
        echo "version_info<<EOF" >> $GITHUB_OUTPUT
        echo "$output" | jq '.' >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Parse Version Info
      id: parse_version
      shell: bash
      run: |
        # Access the version_info from the previous step's output
        version_info="${{ toJson(steps.gitversion.outputs) }}"
        echo "Does this work?"
        echo "$version_info"

    - name: Display GitVersion info
      run: |
        echo "Major Version: ${{ steps.parse_version.outputs.version_major }}"
